---
- name: ensure required packages are installed
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ munin_node_packages }}"

- name: ensure config is latest
  template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    mode: 0644
  notify: restart munin-node

- name: ensure plugin config is latest
  template:
    src: munin-node.j2
    dest: /etc/munin/plugin-conf.d/munin-node
    mode: 0644
  notify: restart munin-node

- name: ensure extra plugins are present
  git:
    repo: https://github.com/munin-monitoring/contrib
    dest: /usr/local/share/munin-plugins
  when: munin_node_extra_plugins
  notify: restart munin-node

- name: ensure plugins are present
  file:
    src: "/usr/share/munin/plugins/{{ item }}"
    dest: "/etc/munin/plugins/{{ item }}"
    state: link
    force: yes
  with_items: "{{ munin_node_plugins_active }}"
  notify: restart munin-node

- name: ensure plugins are absent
  file:
    path: "/etc/munin/plugins/{{ item }}"
    state: absent
    force: yes
  with_items: "{{ munin_node_plugins_disabled }}"
  notify: restart munin-node


- name: delete prior index.html
  file: path="/var/www/html/index.html" owner="root" group="root" state=absent

- name: Copy index.html
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: index.html
      dest: "/var/www/html/index.html"


- name: Create munin www directory
  file: path="/var/www/munin" owner="munin" group="munin" state=directory


- name: ddd
  command: chmod -R 755 /var/www/munin

- name: dddd
  command: chown munin:munin /var/www/munin

- name: permisos munin www directory
  file:
    path: "/var/www/html/munin"
    state: touch
    mode: "u=rw,g=r,o=r"


- name: ensure extra plugins are present
  file:
    src: "/usr/local/share/munin-plugins/plugins/{{ item.path }}"
    dest: "/etc/munin/plugins/{{ item.name }}"
  with_items: "{{ munin_node_extra_plugins_active }}"
  notify: restart munin-node




